### ISSUE TITLE
Game is literally unplayable through Source Code

### ISSUE THREAD

**Issue by Agentsecret24** [this-is-bennyk/FNF-Benjine#1]
When attempting to load into either story mode or freeplay, the UserData.gd file returns the error

Invalid get index 'weeks' (on base: 'null instance').

`211:    for week in song_list.weeks:`
`212:   freeplay_list.append_array(week.song_datas)`

**Comment by this-is-bennyk** [comment]
Looking into it

**Comment by this-is-bennyk** [comment]
Fixed
