### ISSUE TITLE
Can't load 2nd loading screen

### ISSUE THREAD

**Issue by ghost** [this-is-bennyk/FNF-Benjine#10]
When i open the engine, the second loading screen after the mod loading doesn't load:

https://user-images.githubusercontent.com/94700814/174452647-27f10505-3d57-4c48-afab-82dcae26889b.mp4

**Comment by this-is-bennyk** [comment]
I know, uploading a hotfix rn

**Comment by ghost** [comment]
@this-is-bennyk Thanks !
