### ISSUE TITLE
Songs won't play when the project is exported

### ISSUE THREAD

**Issue by Daninnocent** [this-is-bennyk/FNF-Benjine#13]
everything was fine till i gave the build to someone else (who did have a pc with windows installed) when loading a song the stage and chart seems to load but the song doesn't so the charts and characters just seem to freeze in place not even idling

so i tried exporting it to android and sure enough i had this issue

yet it doesn't seem to happen on my pc?

am i doing something wrong? sorry i'm kinda new to godot

 edit: 
btw menus do work but the starting screen didnt even play the freaky menu song and gf seems to freeze in place but the song does start playing at the main menu

**Comment by this-is-bennyk** [comment]
Strange, I'll look into it

**Comment by Daninnocent** [comment]
> Strange, I'll look into it

Any updates on it yet? I still can't find the solution

**Comment by this-is-bennyk** [comment]
Turns out I forgot to include some details that are necessary for exporting the Benjine itself. See [here](https://github.com/this-is-bennyk/FNF-Benjine/wiki/Exporting#the-benjine).
