### ISSUE TITLE
Story Mode crash for Low-End PCs

### ISSUE THREAD

**Issue by johfyakita** [this-is-bennyk/FNF-Benjine#2]
I know my PC is weak as heck, but the vanilla game and other engines do NOT crash when entering Story Mode. Please fix.

**Comment by this-is-bennyk** [comment]
Will look into it, may require GLES2 build

**Comment by johfyakita** [comment]
oh yeah idk if this is necessary but entering Freeplay has no crashes. Only Story Mode does when tried.

**Comment by this-is-bennyk** [comment]
2.0.0 now includes GLES2 builds. Try it out and see if it crashes using those.

**Comment by johfyakita** [comment]
GLES2 fixed the crashing issue. (there would still be crashes if the low-end PC has too many programs opened or has their browser using a lot of memory of course, but it's not really a big problem)
