### ISSUE TITLE
can't do Jacks properly

### ISSUE THREAD

**Issue by johfyakita** [this-is-bennyk/FNF-Benjine#3]
so the jack patterns.. if I try to hit those, the pattern just poof itself out. it disappears

**Comment by ghost** [comment]
Can confirm this bug happens on my side. Attatched is the slow-mo gif of it happening.
![jacks](https://user-images.githubusercontent.com/10368254/171998154-3b7c72a3-90ec-4558-9075-361601547f37.gif)

OS: Windows 10 Education
FNF Benjine V1.0.0

**Comment by this-is-bennyk** [comment]
Changed in 2.0.0
