### ISSUE TITLE
Hold note visual issue? 

### ISSUE THREAD

**Issue by godor-gody** [this-is-bennyk/FNF-Benjine#4]
![Screenshot_20220604-114544_Twitter2](https://user-images.githubusercontent.com/99605832/172066023-9421c4a1-8789-42bc-bec3-a1b3a040e3f9.png)
The hold notes look really weird

**Comment by this-is-bennyk** [comment]
Known issue, will be fixed

**Comment by this-is-bennyk** [comment]
Fixed in 2.0.0
