### ISSUE TITLE
Mac version being damaged and unable to open 

### ISSUE THREAD

**Issue by TFP-Youngjobi** [this-is-bennyk/FNF-Benjine#6]
When trying to download the mac version of Benjine it says its damaged and can not be open.

**Comment by this-is-bennyk** [comment]
Looking into it, will need to find a Mac tester

**Comment by TFP-Youngjobi** [comment]
> 

If you need someone to test if the mac version works then I could do it

**Comment by TFP-Youngjobi** [comment]
if you can't find someone to test it then I could do it.

**Comment by this-is-bennyk** [comment]
Turns out this is a known issue for Godot. Mac versions now include instructions on how to run the game. If I ever get a hold of a Mac computer to properly export the game, it will be truly fixed.
