### ISSUE TITLE
Cannot Open v.2.0.0 project

### ISSUE THREAD

**Issue by johfyakita** [this-is-bennyk/FNF-Benjine#8]
So everytime I open v.2.0 project, the engine stops responding and shows these logs on the console.. There is nothing like this whenever I open the v.1.0.0 project.

![Screenshot (1113)](https://user-images.githubusercontent.com/85341402/173237565-63c3612b-b06d-4ae0-8efd-54f4d2992aaa.png)
![Screenshot (1114)](https://user-images.githubusercontent.com/85341402/173237566-5689eeb1-b3a9-494c-a23a-98d16e4695a1.png)
![Screenshot (1112)](https://user-images.githubusercontent.com/85341402/173237568-ceb47f4c-a22a-4556-977e-6005b13b69e1.png)

**Comment by this-is-bennyk** [comment]
Will investigate for v2.1.0

**Comment by Topicranger** [comment]
Had this happen to me today as well and seems to be caused by faulty import data.
I solved it by manually deleting the contents of /.import and letting the engine reimport everything on startup (which will stop it from responding for a while).

**Comment by this-is-bennyk** [comment]
If that's the case that's not a Benjine thing, that's a Godot thing. Deleting imports is a good idea if you need to refresh the project

**Comment by this-is-bennyk** [comment]
Yeah so basically:
When you open the project for the first time it'll recrete all the missing .import files
A bunch of errors will pop up
They actually don't matter, they're informing you that the .import file is missing and will recreate it for you anyways
Just go to `Project > Reload Current Project` and you'll be good
